CREATE TYPE product_category AS ENUM (
    'Dry Goods',
    'Fruits',
    'Vegetables',
    'Herbs and Spices',
    'Oils',
    'Dressings',
    'Frozen',
    'Canned Foods',
    'Jars',
    'Bottles'
);


CREATE TYPE storage_location AS ENUM(
    'Freezer',
    'Fridge',
    'Pantry'
);

CREATE TYPE product_unit AS ENUM(
    'Jar',
    'Bag',
    'lbs',
    'can',
    'kg',
    'bottle',
    'gallon',
    'pieces',
    'container'
);

CREATE TABLE IF NOT EXISTS groceries (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    category product_category NOT NULL,
    location storage_location NOT NULL,
    expiry_reminder BOOLEAN DEFAULT false,
    expiry_date date DEFAULT now(),
    quantity INTEGER DEFAULT 1 NOT NULL,
    unit product_unit NOT NULL,
    notes text,
    price decimal(12,2) NOT NULL,
    user_id INTEGER REFERENCES users(id),
    image TEXT DEFAULT 'undefined'
);