CREATE TYPE storage_location AS ENUM(
    'Freezer',
    'Fridge',
    'Pantry'
);

CREATE TABLE IF NOT EXISTS groceries (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    location storage_location NOT NULL,
    expiry_reminder BOOLEAN DEFAULT false,
    expiry_date date DEFAULT now(),
    quantity INTEGER DEFAULT 1 NOT NULL,
    unit TEXT NOT NULL,
    notes TEXT,
    price DECIMAL(12,2) DEFAULT 1.00 NOT NULL,
    user_id INTEGER REFERENCES users(id),
    image TEXT DEFAULT 'undefined'
);